stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: iimrankhan98/flask-app
  DOCKER_TAG: latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  tags:
    - microk8s
    
test:
  stage: test
  script:
    - docker rm -f $(docker ps -a -q)
    - docker run -dit --name flask-app1 -p 9090:9090 $DOCKER_IMAGE:$DOCKER_TAG
  tags:
    - microk8s  

deploy:
  stage: deploy
  script:
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  tags:
    - microk8s
